name: 'Minha Action em Python'
description: 'Ação que executa um script Python'
inputs:
  exemplo_entrada:
    description: 'Um exemplo de entrada para o script'
    required: true
    default: 'lc'
runs:
  using: 'composite'
  steps:
    - name: Checar código
      run: echo "Executando a ação..."
      shell: bash

    - name: Executar script Python
      run: |
        python main.py ${{ inputs.exemplo_entrada }}
      shell: bash