name: 'Minha Action em Python'
description: 'Ação que executa um script Python'
inputs:
  nome:
    description: 'O nome do usuário'
    required: true
    default: 'Nome do usuário'

  sobrenome:
    description: 'O nome do usuário'
    required: true
    default: 'Sobrenome do usuário'

  cargo:
    description: 'O cargo do usuário'
    required: true
    default: 'Cargo do usuário'

runs:
  using: 'composite'
  steps:

    - name: Checkout Codigo
      uses: actions/checkout@v4
      with:
        repository: lccinacio/action-python/actions
        path: .

    - name: Checar código
      run: echo "Verificando dados do usúario ..."
      shell: bash

    - name: Executar script Python
      run: |
       actions/python main.py ${{ inputs.nome && inputs.sobrenome && inputs.cargo }}
      shell: bash
      env:
        NOME: ${{ inputs.nome }}
        SOBRENOME: ${{ inputs.sobrenome }}
        CARGO: ${{ inputs.cargo }}