name: Executar minha action

on:
  push:
    branches:
      - main

jobs:
  python-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Usar a ação personalizada
        id: colaborador
        uses: lccinacio/action-python@v3.0.0
        with:
          nome: 'Lucas Bezerra'
          sobrenome: 'Bezerra'
          cargo: 'Engenheiro de qualidade'
